# Generated by Django 3.0.5 on 2020-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='covid',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='gripe_comum',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='h1n1',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
