# Generated by Django 3.0.5 on 2020-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200426_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='covid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='gripe_comum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='h1n1',
            field=models.IntegerField(null=True),
        ),
    ]
