# Generated by Django 3.0.5 on 2020-04-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200426_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='covid',
            field=models.IntegerField(default=8, editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='gripe_comum',
            field=models.IntegerField(default=65, editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='h1n1',
            field=models.IntegerField(default=54, editable=False),
        ),
    ]
