# Generated by Django 3.0.5 on 2020-04-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200426_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='covid',
            field=models.IntegerField(default=72, editable=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='gripe_comum',
            field=models.IntegerField(default=85, editable=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='h1n1',
            field=models.IntegerField(default=86, editable=False),
        ),
    ]
