# Generated by Django 3.0.5 on 2020-04-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200426_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='covid',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='gripe_comum',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='h1n1',
            field=models.IntegerField(editable=False),
        ),
    ]
