# Generated by Django 3.0.5 on 2020-04-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200426_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='covid',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='gripe_comum',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='h1n1',
        ),
        migrations.CreateModel(
            name='exame',
            fields=[
                ('id_exame', models.AutoField(primary_key=True, serialize=False)),
                ('h1n1', models.IntegerField(editable=False, null=True)),
                ('gripe_comum', models.IntegerField(editable=False, null=True)),
                ('covid', models.IntegerField(editable=False, null=True)),
                ('data', models.DateTimeField(editable=False)),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente')),
            ],
        ),
    ]
