# Generated by Django 3.0.5 on 2020-04-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200428_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='Paciente',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.paciente'),
        ),
    ]
