# Generated by Django 3.0.5 on 2020-04-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200428_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='id',
        ),
        migrations.AddField(
            model_name='exame',
            name='id_exame',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
