# Generated by Django 3.0.5 on 2020-04-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200428_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='covid',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='exame',
            name='gripe_comum',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='exame',
            name='h1n1',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
