# Generated by Django 3.0.5 on 2020-04-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200428_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='radiografia',
            field=models.TextField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
