# Generated by Django 3.0.5 on 2020-04-28 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200428_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='data',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
